import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import './PolicySummary.css';
import { FiArrowLeft, FiFileText, FiMessageSquare } from 'react-icons/fi';

/**
 * PolicySummary Component
 * 
 * This component displays a summary of an insurance policy,
 * automatically generated by GPT after the user uploads a PDF.
 */
function PolicySummary() {
  // Navigation hook for redirecting to different pages
  const navigate = useNavigate();
  
  // Get the policy ID from the URL parameters
  const { policyId } = useParams();
  
  // State to store the policy data
  const [policyData, setPolicyData] = useState(null);
  
  // State to store the policy summary
  const [policySummary, setPolicySummary] = useState('');
  
  // State to track loading status
  const [isLoading, setIsLoading] = useState(true);
  
  // State to track error message
  const [errorMessage, setErrorMessage] = useState('');
  
  /**
   * Fetch policy data and generate summary when the component mounts
   */
  useEffect(() => {
    const fetchPolicyData = async () => {
      try {
        // Get the API URL and key from environment variables or use defaults
        const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:8000';
        const apiKey = process.env.REACT_APP_API_KEY || 'policy_decoder_api_key_12345';
        
        // Fetch policy data from the server with API key in header
        const response = await fetch(`${apiUrl}/policy/${policyId}`, {
          headers: {
            'X-API-Key': apiKey
          }
        });
        
        if (!response.ok) {
          throw new Error('Failed to fetch policy data');
        }
        
        const data = await response.json();
        
        // Set the policy data
        setPolicyData(data.policyData);
        
        // Generate policy summary using GPT
        await generatePolicySummary(data.policyData.fullText);
        
        setIsLoading(false);
      } catch (error) {
        console.error('Error fetching policy data:', error);
        setErrorMessage('Failed to fetch policy data. Please try again.');
        setIsLoading(false);
      }
    };
    
    fetchPolicyData();
  }, [policyId]);
  
  /**
   * Generate a summary of the policy using GPT
   * 
   * @param {string} policyText - The full text of the policy
   */
  const generatePolicySummary = async (policyText) => {
    try {
      // Get the API URL and key from environment variables or use defaults
      const apiUrl = process.env.REACT_APP_API_URL || 'http://localhost:8000';
      const apiKey = process.env.REACT_APP_API_KEY || 'policy_decoder_api_key_12345';
      
      // Create the GPT prompt exactly as specified
      const prompt = `You are a Professional Insurance Policy Summarizer. Summarize the insurance policy from the uploaded PDF in 500 characters or less, including coverage, key exclusions, and one notable feature (e.g., premium or deductible). Use only the document's text, saying 'Unclear' if details are missing. Avoid advice or external info. Keep it factual and concise. End with: 'Click "Chat with Your Policy" for details.'`;
      
      // Call the GPT API to generate a summary
      const response = await fetch(`${apiUrl}/summarize`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-API-Key': apiKey
        },
        body: JSON.stringify({
          policyText: policyText.substring(0, 10000), // Limit text length to avoid API issues
          prompt: prompt
        })
      });
      
      if (!response.ok) {
        // If the API call fails, use a fallback summary
        setPolicySummary('This policy appears to provide standard insurance coverage with typical exclusions and conditions. For specific details about your coverage, limits, and exclusions, please use the "Chat with Your Policy" feature below.');
        return;
      }
      
      const data = await response.json();
      
      // Set the policy summary
      setPolicySummary(data.summary);
    } catch (error) {
      console.error('Error generating policy summary:', error);
      // Use a fallback summary if the API call fails
      setPolicySummary('This policy appears to provide standard insurance coverage with typical exclusions and conditions. For specific details about your coverage, limits, and exclusions, please use the "Chat with Your Policy" feature below.');
    }
  };
  
  /**
   * handleBackClick
   * 
   * Navigates back to the upload policy page
   */
  const handleBackClick = () => {
    navigate('/upload-policy');
  };
  
  /**
   * handleAskQuestion
   * 
   * Navigates to the chat page for asking questions about the policy
   */
  const handleAskQuestion = () => {
    // Navigate to the chat page with the policy ID
    navigate(`/chat/${policyId}`);
  };
  
  // If loading, show a loading state
  if (isLoading) {
    return (
      <div className="data-protection-page">
        <header className="modern-header">
          <div className="logo">
            <img src="/Images/logo2.png" alt="CoverScan Logo" className="header-logo" />
          </div>
          <nav className="main-nav">
            <a href="/">Home</a>
          </nav>
        </header>
        
        <section className="data-protection-section">
          <div className="data-protection-container">
            <div className="policy-loading">
              <div className="loading-spinner"></div>
              <p>Analyzing your policy...</p>
            </div>
          </div>
        </section>
        
        <footer className="modern-footer">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="footer-logo">
                <img src="/Images/logo2.png" alt="CoverScan Logo" className="footer-logo-img" />
              </div>
              <p className="footer-tagline">Making insurance transparent</p>
            </div>
            <div className="footer-links">
              <div className="footer-column">
                <h4>Product</h4>
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/data-protection">Data Protection</a>
              </div>
              <div className="footer-column">
                <h4>Resources</h4>
                <a href="/blog">Blog</a>
                <a href="/faq">FAQ</a>
                <a href="/support">Support</a>
              </div>
              <div className="footer-column">
                <h4>Company</h4>
                <a href="/careers">Careers</a>
                <a href="/contact">Contact</a>
                <a href="/privacy">Privacy Policy</a>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; {new Date().getFullYear()} CoverScan. All rights reserved.</p>
          </div>
        </footer>
      </div>
    );
  }
  
  // If there's an error, show an error message
  if (errorMessage) {
    return (
      <div className="data-protection-page">
        <header className="modern-header">
          <div className="logo">
            <img src="/Images/logo2.png" alt="CoverScan Logo" className="header-logo" />
          </div>
          <nav className="main-nav">
            <a href="/">Home</a>
          </nav>
        </header>
        
        <section className="data-protection-section">
          <div className="data-protection-container">
            <div className="policy-error">
              <p>{errorMessage}</p>
              <button className="back-button" onClick={handleBackClick}>
                <FiArrowLeft /> Back to Upload
              </button>
            </div>
          </div>
        </section>
        
        <footer className="modern-footer">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="footer-logo">
                <img src="/Images/logo2.png" alt="CoverScan Logo" className="footer-logo-img" />
              </div>
              <p className="footer-tagline">Making insurance transparent</p>
            </div>
            <div className="footer-links">
              <div className="footer-column">
                <h4>Product</h4>
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/data-protection">Data Protection</a>
              </div>
              <div className="footer-column">
                <h4>Resources</h4>
                <a href="/blog">Blog</a>
                <a href="/faq">FAQ</a>
                <a href="/support">Support</a>
              </div>
              <div className="footer-column">
                <h4>Company</h4>
                <a href="/careers">Careers</a>
                <a href="/contact">Contact</a>
                <a href="/privacy">Privacy Policy</a>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; {new Date().getFullYear()} CoverScan. All rights reserved.</p>
          </div>
        </footer>
      </div>
    );
  }
  
  // If no policy data is available, show an error
  if (!policyData) {
    return (
      <div className="data-protection-page">
        <header className="modern-header">
          <div className="logo">
            <img src="/Images/logo2.png" alt="CoverScan Logo" className="header-logo" />
          </div>
          <nav className="main-nav">
            <a href="/">Home</a>
          </nav>
        </header>
        
        <section className="data-protection-section">
          <div className="data-protection-container">
            <div className="policy-error">
              <p>No policy data available. Please try uploading your policy again.</p>
              <button className="back-button" onClick={handleBackClick}>
                <FiArrowLeft /> Back to Upload
              </button>
            </div>
          </div>
        </section>
        
        <footer className="modern-footer">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="footer-logo">
                <img src="/Images/logo2.png" alt="CoverScan Logo" className="footer-logo-img" />
              </div>
              <p className="footer-tagline">Making insurance transparent</p>
            </div>
            <div className="footer-links">
              <div className="footer-column">
                <h4>Product</h4>
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/data-protection">Data Protection</a>
              </div>
              <div className="footer-column">
                <h4>Resources</h4>
                <a href="/blog">Blog</a>
                <a href="/faq">FAQ</a>
                <a href="/support">Support</a>
              </div>
              <div className="footer-column">
                <h4>Company</h4>
                <a href="/careers">Careers</a>
                <a href="/contact">Contact</a>
                <a href="/privacy">Privacy Policy</a>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; {new Date().getFullYear()} CoverScan. All rights reserved.</p>
          </div>
        </footer>
      </div>
    );
  }
  
  return (
    <div className="data-protection-page">
      {/* Header */}
      <header className="modern-header">
        <div className="logo">
          <img src="/Images/logo2.png" alt="CoverScan Logo" className="header-logo" />
        </div>
        <nav className="main-nav">
          <a href="/">Home</a>
          <a href="#policy-summary">Policy Summary</a>
          <a href="#chat-with-policy">Chat with Policy</a>
        </nav>
      </header>

      {/* Main Content */}
      <section className="data-protection-section">
        <div className="data-protection-container">
          <h1 className="data-protection-title">Policy Summary</h1>
          <p className="data-protection-tagline">
            Your insurance policy simplified and explained.
          </p>

          <div className="data-protection-content">
            <button className="back-button" onClick={handleBackClick}>
              <FiArrowLeft /> Back to Upload
            </button>
            
            <div id="policy-summary" className="policy-summary-content">
              <h2 className="section-heading">Your Policy at a Glance</h2>
              <div className="policy-summary-box">
                <div className="policy-summary-icon">
                  <FiFileText size={40} />
                </div>
                <div className="policy-summary-text">
                  <h3>{policyData.name}</h3>
                  <p>{policySummary}</p>
                </div>
              </div>
            </div>

            <div id="chat-with-policy" className="chat-with-policy-section">
              <h2 className="section-heading">Have Questions About Your Policy?</h2>
              <p>
                Our AI assistant can answer specific questions about your policy coverage, exclusions, and conditions.
              </p>
              <div className="chat-button-container">
                <button className="chat-button" onClick={handleAskQuestion}>
                  <FiMessageSquare size={20} />
                  Chat with Your Policy
                </button>
              </div>
            </div>

            <div className="info-box">
              <h3>How We Process Your Policy</h3>
              <ol className="data-handling-steps">
                <li>
                  <strong>Secure Upload:</strong> Your document is transmitted to our servers using TLS encryption.
                </li>
                <li>
                  <strong>Temporary Processing:</strong> The document is temporarily held in an isolated, secure environment for processing.
                </li>
                <li>
                  <strong>AI Analysis:</strong> Our AI analyzes the document to extract and summarize key information.
                </li>
                <li>
                  <strong>Interactive Session:</strong> You can interact with the analysis results during your session.
                </li>
                <li>
                  <strong>Complete Removal:</strong> Once your session ends, all document data is permanently removed from our systems.
                </li>
              </ol>
            </div>

            <div className="data-protection-conclusion">
              <p>
                At CoverScan, we believe that you shouldn't have to sacrifice privacy for convenience. Our commitment to protecting your data is unwavering, and we continuously work to improve our security measures.
              </p>
              <p>
                If you have any questions about our data protection practices, please don't hesitate to <a href="mailto:privacy@coverscan.com">contact us</a>.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="modern-footer">
        <div className="footer-content">
          <div className="footer-brand">
            <div className="footer-logo">
              <img src="/Images/logo2.png" alt="CoverScan Logo" className="footer-logo-img" />
            </div>
            <p className="footer-tagline">Making insurance transparent</p>
          </div>
          <div className="footer-links">
            <div className="footer-column">
              <h4>Product</h4>
              <a href="/">Home</a>
              <a href="/about">About</a>
              <a href="/data-protection">Data Protection</a>
            </div>
            <div className="footer-column">
              <h4>Resources</h4>
              <a href="/blog">Blog</a>
              <a href="/faq">FAQ</a>
              <a href="/support">Support</a>
            </div>
            <div className="footer-column">
              <h4>Company</h4>
              <a href="/careers">Careers</a>
              <a href="/contact">Contact</a>
              <a href="/privacy">Privacy Policy</a>
            </div>
          </div>
        </div>
        <div className="footer-bottom">
          <p>&copy; {new Date().getFullYear()} CoverScan. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

export default PolicySummary; 